# .goreleaser.yml
# Build customization
builds:
  # makefile currently relies on this name
  - binary: go-hello-server
    main: ./cmd/hello-server/hello-server.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  