# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/darahayes/go-hello-server

    docker:
      - image: circleci/golang:1.10
    
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make build
      - run: make test_cover
      - run: /go/bin/goveralls -coverprofile=coverage-all.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

  docker_push_master:
    working_directory: /go/src/github.com/darahayes/go-hello-server
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make setup
      - setup_remote_docker
      - run: make build_linux
      - run: make docker_build_master
      - run: make docker_push_master

  docker_release:
    working_directory: /go/src/github.com/darahayes/go-hello-server
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make setup
      - run: curl -sL https://raw.githubusercontent.com/goreleaser/get/master/get | bash
      - setup_remote_docker
      - run: make docker_build_release
      - run: make docker_push_release
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /\d\.\d\.\d/
            branches:
              ignore: /.*/
