# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/darahayes/go-hello-server

    docker:
      - image: circleci/golang:1.10
    
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make build
      - run: make test_cover
      - run: /go/bin/goveralls -coverprofile=coverage-all.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

  docker_push_master:
    working_directory: /go/src/github.com/darahayes/go-hello-server
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make setup
      - setup_remote_docker
      - run: make build_linux
      - run: make docker_build_master
      - run: make docker_push_master

  docker_release:
    working_directory: /go/src/github.com/darahayes/go-hello-server
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make setup
      - run: curl -sL https://raw.githubusercontent.com/goreleaser/get/master/get | bash
      - setup_remote_docker
      - run: make docker_build_release
      - run: make docker_push_release
      - store_artifacts:
          path: dist

  oc_deploy:
    working_directory: /go/src/github.com/darahayes/go-hello-server
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: wget https://github.com/openshift/origin/releases/download/v3.7.2/openshift-origin-client-tools-v3.7.2-282e43f-linux-64bit.tar.gz
      - run: tar -xf openshift-origin-client-tools-v3.7.2-282e43f-linux-64bit.tar.gz --strip-components=1 -C . openshift-origin-client-tools-v3.7.2-282e43f-linux-64bit/oc
      - run: chmod +x oc
      - run: ./oc login https://api.starter-us-west-2.openshift.com --token=$OPENSHIFT_TOKEN
      - run: ./oc project $OPENSHIFT_PROJECT
      - run: ./oc import-image $OPENSHIFT_IMAGESTREAM

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /\d\.\d\.\d/
            branches:
              ignore: /.*/
      - oc_deploy:
          requires:
            - build
            - docker_release
          filters:
            tags:
              only: /\d\.\d\.\d/
            branches:
              ignore: /.*/
